"""init users and alerts

Revision ID: 601351e6640b
Revises: 
Create Date: 2026-03-01 14:21:50.664806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601351e6640b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'price', 'direction', 'mode', name='uq_alert_dedupe')
    )
    op.create_index('ix_alerts_active', 'alerts', ['is_active'], unique=False)
    op.create_index('ix_alerts_symbol_active', 'alerts', ['symbol', 'is_active'], unique=False)
    op.create_index('ix_alerts_user_active', 'alerts', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_user_active', table_name='alerts')
    op.drop_index('ix_alerts_symbol_active', table_name='alerts')
    op.drop_index('ix_alerts_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    # ### end Alembic commands ###
